### ISSUE TITLE
mod冲突问题。gt6u和TechReborn冲突。

### ISSUE THREAD

**Issue by DogeNuclearPowerPlant** [GregTech6-Unofficial/GregTech6-Unofficial#43]
Forge版本：10.13.4.1614

 使用的mod：
![QQ截图20210317173752](https://user-images.githubusercontent.com/80572056/111446908-dd4a6480-8747-11eb-95aa-41f77a837da5.png)

<details>
<summary>错误报告</summary>

```java
---- Minecraft Crash Report ----
// You're mean.

Time: 21-3-17 下午4:10
Description: Initializing game

java.lang.RuntimeException: ambiguous recipe: [[1xgt.meta.ore.normal.endstone@8339, 1xgt.meta.ore.normal.netherrack@8339, 1xgt.meta.ore.normal.sandstone@8339, 1xgt.meta.ore.normal.default@8339, 1xgt.meta.ore.broken.endstone@8339, 1xgt.meta.ore.broken.netherrack@8339, 1xgt.meta.ore.broken.sandstone@8339, 1xgt.meta.ore.broken.default@8339, 1xgt.meta.ore.broken.prismarine.dark@8339, 1xgt.meta.ore.normal.prismarine.dark@8339, 1xgt.meta.ore.broken.prismarine.light@8339, 1xgt.meta.ore.normal.prismarine.light@8339, 1xgt.meta.ore.broken.quartzite@8339, 1xgt.meta.ore.normal.quartzite@8339, 1xgt.meta.ore.broken.kimberlite@8339, 1xgt.meta.ore.normal.kimberlite@8339, 1xgt.meta.ore.broken.blueschist@8339, 1xgt.meta.ore.normal.blueschist@8339, 1xgt.meta.ore.broken.greenschist@8339, 1xgt.meta.ore.normal.greenschist@8339, 1xgt.meta.ore.broken.komatiite@8339, 1xgt.meta.ore.normal.komatiite@8339, 1xgt.meta.ore.broken.andesite@8339, 1xgt.meta.ore.normal.andesite@8339, 1xgt.meta.ore.broken.diorite@8339, 1xgt.meta.ore.normal.diorite@8339, 1xgt.meta.ore.broken.granite@8339, 1xgt.meta.ore.normal.granite@8339, 1xgt.meta.ore.broken.limestone@8339, 1xgt.meta.ore.normal.limestone@8339, 1xgt.meta.ore.broken.marble@8339, 1xgt.meta.ore.normal.marble@8339, 1xgt.meta.ore.broken.basalt@8339, 1xgt.meta.ore.normal.basalt@8339, 1xgt.meta.ore.broken.redgranite@8339, 1xgt.meta.ore.normal.redgranite@8339, 1xgt.meta.ore.broken.blackgranite@8339, 1xgt.meta.ore.normal.blackgranite@8339] -> [10xgt.meta.dust@8339]]
	at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
	at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:40)
	at techreborn.compat.recipes.RecipesIC2.addTRMaceratorRecipes(RecipesIC2.java:1269)
	at techreborn.compat.recipes.RecipesIC2.init(RecipesIC2.java:53)
	at techreborn.Core.init(Core.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
	at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:40)
	at techreborn.compat.recipes.RecipesIC2.addTRMaceratorRecipes(RecipesIC2.java:1269)
	at techreborn.compat.recipes.RecipesIC2.init(RecipesIC2.java:53)
	at techreborn.Core.init(Core.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4429260752 bytes (4224 MB) / 5251268608 bytes (5008 MB) up to 5251268608 bytes (5008 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx5000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	GT_ASM{6.14.01} [Greg-ASM®] (minecraft.jar) 
	UCHI	FastCraft{1.25} [FastCraft] (Fastcraft 1.25.jar) 
	UCHI	gregapi{GT6-MC1710} [Greg-API] (GregTech 6.15.07 U-TFR.jar) 
	UCHI	IC2{2.2.828-experimental} [IndustrialCraft 2] (IndustrialCraft 2 Experimental 2.2.828.jar) 
	UCHI	gregapi_post{GT6-MC1710} [Greg-API-Post] (GregTech 6.15.07 U-TFR.jar) 
	UCHI	gregtech{GT6-MC1710} [GregTech 6 Unofficial] (GregTech 6.15.07 U-TFR.jar) 
	UCHI	reborncore{1.1.0.15} [RebornCore] (RebornCore 1.1.0.15.jar) 
	UCHE	techreborn{0.7.21.1131} [TechReborn] (TechReborn 0.7.21.1131.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila 1.5.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4526' Renderer: 'Intel(R) HD Graphics 530'
	Launched Version: HMCL 3.3.172
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4526, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```
</details>

**Comment by DogeNuclearPowerPlant** [comment]
截图少了gt6，使用的GregTech6u版本号是6.15.07。

**Comment by quentin452** [comment]
do you have forgemultipart in 1.7.10 folder , delete it

**Comment by DogeNuclearPowerPlant** [comment]
@quentin452 Thx，but I don't use TechReborn now.
