### ISSUE TITLE
使用含水炼药锅清洗粉碎含油页岩矿石导致崩溃

### ISSUE THREAD

**Issue by henryrabbit** [GregTech6-Unofficial/GregTech6-Unofficial#51]
使用含水炼药锅清洗粉碎含油页岩矿石（Crushed Oil Shale Ore 4472:9853）导致崩溃。
该崩溃导致了游戏存档损坏，因为每次打开都会重复此Bug。

问题似乎在于洗矿时尝试为没有副产物的含油页岩矿石随机副产物，导致Random.nextInt()参数为0，而参数需要一个大于0的数。
崩溃只在使用炼药锅洗矿时出现，使用洗矿机没有该问题。

崩溃报告如下
```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 10/16/21 7:01 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at gregapi.util.UT$Code.select(UT.java:1479)
	at gregapi.oredict.listeners.OreDictListenerItem_Washing.onTickWorld(OreDictListenerItem_Washing.java:69)
	at gregapi.GT_API_Proxy.onWorldTick(GT_API_Proxy.java:565)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_GT_API_Proxy_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.15.0-91-generic
	Java Version: 1.8.0_292, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1935316480 bytes (1845 MB) / 6361710592 bytes (6067 MB) up to 6361710592 bytes (6067 MB)
	JVM Flags: 2 total; -Xms5G -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.7.5.1290} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OmniOcularCore{1.0} [Omni Ocular Core] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	GT_ASM{6.14.11} [Greg-ASM®] (minecraft.jar) 
	UCHIJAAAA	FoamFixCore{1.0.0-beta3} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	gregapi{GT6-MC1710} [Greg-API] (!!gregtech_1.7.10-6.15.08-unofficial.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (!!appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (!!Botania+r1.8-249.jar) 
	UCHIJAAAA	Avaritia{1.13} [Avaritia] (!!Avaritia-1.13.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (!!Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	OpenComputers{1.7.5.1290} [OpenComputers] (!!OpenComputers-MC1.7.10-1.7.5.1290-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (!extrautilities-1.2.12.jar) 
	UCHIJAAAA	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (!IronBackpacks-1.7.10-1.2.20.jar) 
	UCHIJAAAA	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (!OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCHIJAAAA	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) 
	UCHIJAAAA	gregapi_post{GT6-MC1710} [Greg-API-Post] (!!gregtech_1.7.10-6.15.08-unofficial.jar) 
	UCHIJAAAA	gregtech{GT6-MC1710} [GregTech 6 Unofficial] (!!gregtech_1.7.10-6.15.08-unofficial.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.1} [Better Builder's Wands] (!BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJAAAA	HoloInventory{1.9.1.124} [HoloInventory] (!HoloInventory-1.7.10-1.9.1.124.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b200.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.0-beta3.jar) 
	UCHIJAAAA	nechar{1.0} [Not Enough Characters] (NotEnoughCharacters-1.7.10-1.0.jar) 
	UCHIJAAAA	OmniOcular{1.7.10-1.0build103} [Omni Ocular] (OmniOcular-1.7.10-1.0build103.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	ae2wct{1.7.10-rv3-1.8.7.9b} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 5; [EntityPlayerMP['EDCollion'/92396004, l='world', x=58.07, y=68.00, z=-39.44], EntityPlayerMP['Henry_rabbit'/92622960, l='world', x=-21.24, y=10.00, z=0.11]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```
希望尽快修复该bug，并让损坏的游戏存档能够重新使用。

**Comment by henryrabbit** [comment]
通过mcedit编辑地图删除炼药锅已经修复了存档，但仍期待bug解决。
